name: Deploy Bundle Images to GHCR
env:
  DOTNET_VERSION: '6.0.x'
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
      push-bundle-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: '.'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Bundle Image'
            env:
             VERSION: $(git describe --tags --abbrev=0 || echo "0.1.0")
             IMAGE_TAG_BASE: ghcr.io/${{ github.repository }}:$VERSION
             BUNDLE_IMG: ghcr.io/${{ github.repository }}:$VERSION-bundle:v$VERSION
             BUNDLE_GEN_FLAGS: -q --overwrite --version $VERSION --extra-service-accounts "linuxptp-daemon"
            run: |
              make bundle
              make bundle-build
              make bundle-push

